### ISSUE TITLE
shapeless 2.3 causes "could not find implicit value" compilation error

### ISSUE THREAD

**Issue by olafurpg** [alexarchambault/case-app#38]
The automatic `Parser` derivation doesn't seem to work with shapeless 2.3. See this ammonite session

```scala
$ amm
@ load.ivy("com.chuusai" %% "shapeless" % "2.3.1")

@ load.ivy("com.github.alexarchambault" %% "case-app" % "1.0.0-RC3")

@ import caseapp._
import caseapp._
@ case class HasStr(str: String)
defined class HasStr
@ CaseApp.parse[HasStr](Seq("--str", "banana"))
cmd4.sc:1: could not find implicit value for evidence parameter of type caseapp.Parser[$sess.cmd3.HasStr]
val res4 = CaseApp.parse[HasStr](Seq("--str", "banana"))
                                ^
Compilation Failed
@
```

If I remove the first line that loads shapeless 2.3 the compilation error goes away. My project transitively pulled in shapeless 2.3 via another dependency.

**Comment by alexarchambault** [comment]
The `1.1.x` branch (so version `1.1.0-RC3`) is compatible with shapeless 2.3. The 1.0.x versions target shapeless 2.2 only.

**Comment by olafurpg** [comment]
My bad, depending on 1.1.0-RC3 fixes the issue. I had not realised there was 1.1.x and 1.0.x.

**Comment by alexarchambault** [comment]
I should make that clearer in the README :-| (which is confusing in its current state).
